### ISSUE TITLE
It is  impossible to determine the transaction order in a slot.

### ISSUE THREAD

**Issue by lijunwangs** [solana-labs/solana-accountsdb-plugin-postgres#19]
It is impossible to determine the transaction order in a slot as when we save the transaction it is done by multiple threads in parallel.

Solution:
Use an extra field to indicate the ordering of the transaction.

**Comment by mvines** [comment]
Careful here though: the order of transactions within an entry is undefined. Each validator intentionally executes them in random order.  

For full expressiveness, I suggest two fields:
1. The block entry the transaction can be found in
2. The "natural" order of the transaction within the entry. That is, how they were ordered within the shred. This will be consistent across the network, even though in practice the execution order may have been different.

This is a level of info that the RPC API does not expose even but is quite useful at times.

**Comment by lijunwangs** [comment]
Thanks for the background info @mvines : I think we are looking for the same order as if these transactions are loaded from the block store for a block.

**Comment by mvines** [comment]
Cool.  Include the Entry index for each transaction in the block too please
