### ISSUE TITLE
error when compiling plugin: error[E0658]: destructuring assignments are unstable

### ISSUE THREAD

**Issue by dancamarg0** [solana-labs/solana-accountsdb-plugin-postgres#25]
I'm getting the above error when I try to compile the latest version of the plugin.

It appears to be a new error as I have already compiled older versions successfully.

Full backtrace:

```
error[E0658]: destructuring assignments are unstable
   --> /home/solana/.cargo/registry/src/github.com-1ecc6299db9ec823/solana-runtime-1.10.12/src/cost_model.rs:100:71
    |
100 |         (tx_cost.builtins_execution_cost, tx_cost.bpf_execution_cost) =
    |         ------------------------------------------------------------- ^
    |         |
    |         cannot assign to this expression
    |
    = note: see issue #71126 <https://github.com/rust-lang/rust/issues/71126> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `solana-runtime` due to previous error

```

**Comment by dancamarg0** [comment]
Using wrapped cargo from solana v1.9.22 but i get the same error from v1.9.13 which I have compiled successfully in the past

```
solana@pit7:~/solana-accountsdb-plugin-postgres$ ../solana/cargo --version
+ exec cargo +1.57.0 --version
cargo 1.57.0 (b2e52d7ca 2021-10-21)
```

**Comment by linuskendall** [comment]
@dancamarg0 i see that this version of the plugin is using the 1.10.7 runtime and this is probably why you are getting it, because 1.10 is meant to be built with rust 1.59.

**Comment by dancamarg0** [comment]
Oh ok, yes I confirm that works thanks @linuskendall 

I'll close this issue, but it might be worth to consider to add releases / tags so we can go back in versions?
