### ISSUE TITLE
memory allocation of 140450800187792 bytes failed

### ISSUE THREAD

**Issue by valentinmadrid** [solana-labs/solana-accountsdb-plugin-postgres#56]
I am using solana-test-validator with the Solana AccountsDB Plugin.
On the validator logs, everything looks normal but everytime I run it, I get the error: memory allocation of 140450800187792 bytes failed and the process aborts.
Solana CLI Version = 1.15.2
Accountsdb Version = 1.15.2
Rust Version = 1.66.1

My test validator works, and other Geyser Plugins such as mvines example plugin also work.

**Comment by valentinmadrid** [comment]
Also getting capacity overflow error:
thread '<unnamed>' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:525:5
stack backtrace:
[0m[38;5;8m[[0m2023-04-26T11:47:18.040470005Z [0m[32mINFO [0m solana_streamer::streamer[0m[38;5;8m][0m streamer send Gossip hosts: count:1 [(127.0.0.1, SendStats { bytes: 132, count: 1 })]
[0m[38;5;8m[[0m2023-04-26T11:47:18.040477775Z [0m[32mINFO [0m solana_metrics::metrics[0m[38;5;8m][0m datapoint: Gossip streamer-send-sample_duration_ms=0i streamer-send-host_count=1i streamer-send-bytes_total=132i streamer-send-pkt_count_total=1i streamer-send-host_bytes_min=132i streamer-send-host_bytes_max=132i streamer-send-host_bytes_mean=132i streamer-send-host_bytes_90pct=132i streamer-send-host_bytes_50pct=132i streamer-send-host_bytes_10pct=132i
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: alloc::raw_vec::capacity_overflow
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/raw_vec.rs:525:5
   3: solana_geyser_plugin_postgres::postgres_client::ParallelPostgresClient::update_account
   4: <solana_geyser_plugin_postgres::geyser_plugin_postgres::GeyserPluginPostgres as solana_geyser_plugin_interface::geyser_plugin_interface::GeyserPlugin>::update_account
   5: solana_geyser_plugin_manager::accounts_update_notifier::AccountsUpdateNotifierImpl::notify_plugins_of_account_update
   6: <solana_geyser_plugin_manager::accounts_update_notifier::AccountsUpdateNotifierImpl as solana_runtime::accounts_update_notifier_interface::AccountsUpdateNotifierInterface>::notify_account_update
   7: solana_runtime::accounts_db::geyser_plugin_utils::<impl solana_runtime::accounts_db::AccountsDb>::notify_account_at_accounts_update
   8: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   9: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  10: solana_runtime::accounts_db::AccountsDb::store_accounts_custom
  11: solana_runtime::accounts_db::AccountsDb::store
  12: solana_runtime::accounts::Accounts::store_cached
  13: solana_runtime::bank::Bank::commit_transactions
  14: solana_core::banking_stage::committer::Committer::commit_transactions
  15: solana_core::banking_stage::BankingStage::process_and_record_transactions
  16: solana_core::banking_stage::BankingStage::process_packets_transactions
  17: solana_core::banking_stage::BankingStage::do_process_packets
  18: solana_core::unprocessed_transaction_storage::UnprocessedTransactionStorage::process_packets
  19: solana_core::banking_stage::BankingStage::process_loop

**Comment by valentinmadrid** [comment]
UPDATE: Turns out the account.owner field does not return a 32 byte Public Key, but either an array of 11832580360 or 6378577992 bytes.
Looks like it's a problem coming from the Geyser Plugin Interface itself.

**Comment by CriesofCarrots** [comment]
While I haven't reproduced your specific issue, typically crashes of this kind occur when a geyser plugin wasn't compiled with the same rust and solana versions as the solana-test-validator. I recommend double-checking the versions of the plugin and test-validator and recompiling.

**Comment by valentinmadrid** [comment]
> While I haven't reproduced your specific issue, typically crashes of this kind occur when a geyser plugin wasn't compiled with the same rust and solana versions as the solana-test-validator. I recommend double-checking the versions of the plugin and test-validator and recompiling.

Deployed on a fresh Ubuntu Instance and it worked indeed. Is there any way to check if versions match and throw them into the Startup Log ? That would definitely help.

**Comment by gwertem** [comment]
I banged my head trying to fix memory allocation and segfault issues, even tried on different computers without success. Here's a stable configuration that works

- Plugin commit: [68a4471214cbca1ef9031410ce03f51960f44e2e](https://github.com/solana-labs/solana-accountsdb-plugin-postgres/commit/68a4471214cbca1ef9031410ce03f51960f44e2e)

- Rustc version 1.69.0 (from [ci/rust-version.sh](https://github.com/solana-labs/solana-accountsdb-plugin-postgres/blob/68a4471214cbca1ef9031410ce03f51960f44e2e/ci/rust-version.sh#L21))

- Solana version `1.16.17`.
  - Important: Add `bumpalo = { version = "=3.14.0" }` to Cargo.toml in the plugin code. The latest `bumpalo` needs a newer version of Rust, so it will refuse to compile otherwise.
  
 - Postgres version is not a problem. Version 16 worked for me.
 
 - No need to build Solana from source.
 
 You guys should test the latest commit and post the version requirements in readme.

**Comment by p14041999** [comment]
This might need some sort of Attention.

Incompatible with latest solana cli stable release v2.1.20

And 
`memory allocation of 140018624037376 bytes failed` error persists
