### ISSUE TITLE
What value for "host" in the config file?

### ISSUE THREAD

**Issue by ashpoolin** [solana-labs/solana-accountsdb-plugin-postgres#57]
I've gotten the geyser postgres plugin v1.14.17 compiled and configured, just waiting on node to sync. Postgres database is on localhost. One question I have that doesn't seem to be answered anywhere is: what value do you put in for "host" in the config file? Ex:
cat geyser-plugin-config-postgres.json 
{
    "libpath": "/home/solana/solana-accountsdb-plugin-postgres/target/debug/libsolana_geyser_plugin_postgres.so",
    "host": "localhost",
    "user": "solana",
    "port": 5432,
    "threads": 20,
    "batch_size": 20,
    "panic_on_db_errors": true,
    "transaction_selector" : {
        "mentions" : \["TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA", "11111111111111111111111111111111"\],
    }
}

Originally, it's "postgres-server" but could it be "localhost", or is this a prompt to insert an IP address (e.g. 127.0.0.1)?

Thanks!

**Comment by lijunwangs** [comment]
It is documented here: https://github.com/solana-labs/solana-accountsdb-plugin-postgres/blob/master/src/geyser_plugin_postgres.rs#L39

It is the DNS name or IP of the postgres server, if it is on your localhost, yes, you should be able to use "localhost".
